### ISSUE TITLE
Youtube or Vimeo

### ISSUE THREAD

**Issue by JLBA** [heimrichhannot/contao-news_media#2]
Hello,

Is it possible to use YT or Vimeo url in External link ? I tried [https://youtu.be/79DEa1JTqNA](https://youtu.be/79DEa1JTqNA) but it just shows an audio mediaplayer with no audio (and no video). 

Thanks for your help.

**Comment by koertho** [comment]
Hi, for youtube/vimeo you can use the build-in video-player of contao or our [video bundle](https://github.com/heimrichhannot/contao-video-bundle)

**Comment by JLBA** [comment]
Thanks for your answer.

But I forgot to specify I was hoping to use YT or Vi video directly in 
newslist in place of image. is there a solution ?

Le 27/02/2023 à 08:08, Thomas a écrit :

**Comment by koertho** [comment]
Video bundle has a news integration. You need just some litte template adjustments

**Comment by JLBA** [comment]
Ok. So I can use your plugin for the database field but core video 
player instead of your video player ?

Le 27/02/2023 à 10:48, Thomas a écrit :
> Video bundle has a news integration. You need just some litte template 
> adjustments

**Comment by koertho** [comment]
Use the video-bundle mentioned above, so you can output a video player in your news.
